"""Add thumbnail_url column to writeups

Revision ID: add_thumbnail_url
Revises: a614efcbbdc5
Create Date: 2025-12-09 11:12:55.492627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_thumbnail_url'
down_revision: Union[str, None] = 'a614efcbbdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeups', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeups', 'thumbnail_url')
    # ### end Alembic commands ###
